.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. alphapay_qt test_alphapay_qt
clean: FORCE
	$(MAKE) -C .. alphapay_qt_clean test_alphapay_qt_clean
check: FORCE
	$(MAKE) -C .. test_alphapay_qt_check
alphapay-qt alphapay-qt.exe: FORCE
	 $(MAKE) -C .. alphapay_qt
